### ISSUE TITLE
Not working with bspwm

### ISSUE THREAD

**Issue by candreslobor** [morrolinux/i3expo-ng#13]
Everytime i launch the app it throws me this message:

```
Traceback (most recent call last):
  File "/home/candres/.local/bin/i3expod.py", line 65, in <module>
    i3 = i3ipc.Connection()
  File "/usr/lib/python3.9/site-packages/i3ipc/connection.py", line 68, in __init__
    raise Exception('Failed to retrieve the i3 or sway IPC socket path')
Exception: Failed to retrieve the i3 or sway IPC socket path
```

**Comment by aleemont** [comment]
This project is meant to work on i3wm.
