### ISSUE TITLE
Trying to package 

### ISSUE THREAD

**Issue by Tonus1** [morrolinux/i3expo-ng#26]
Hi
I'm trying to make a buildscript (SlackBuilds for Slackware-15.0) for i3expo-ng and all it dependencies.
Everything builds fine but pytest-asyncio for now.

The program generates the temporary workspace but with no screenshots and this error
```
Traceback (most recent call last):
  File "/usr/lib64/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/bin/i3expod.py", line 396, in show_ui
    qm = pygame.font.SysFont('sans-serif', 550).render('?', True, (150, 150, 150))
  File "/usr/lib64/python3.9/site-packages/pygame/sysfont.py", line 436, in SysFont
    return constructor(fontname, size, set_bold, set_italic)
  File "/usr/lib64/python3.9/site-packages/pygame/sysfont.py", line 354, in font_constructor
    font = Font(fontpath, size)
  File "/usr/lib64/python3.9/site-packages/pygame/pkgdata.py", line 27, in <module>
    from pkg_resources import resource_stream, resource_exists
  File "/usr/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'xdg' distribution was not found and is required by i3expod
```
Is it related to the missing pytest-asyncio dependency ?

Or a missing one ?

I have 
```
pyxdg-0.27-x86_64-6
xdg-dbus-proxy-0.1.2-x86_64-1_SBo
xdg-desktop-portal-1.12.1-x86_64-1
xdg-desktop-portal-kde-5.23.5-x86_64-1
xdg-user-dirs-0.17-x86_64-3
xdg-utils-1.1.3-noarch-4
```

Are already avaible if needed
```
NAME                                         VERSION
desktop/libqtxdg                          3.10.0
desktop/slackware-xdg-menu      0.7.6.2
desktop/xdg-desktop-portal-gtk   1.4.0
desktop/xdgmenumaker              2.0
libraries/libxdg-basedir                1.2.3
system/qtxdg-tools                      3.10.0
system/xdg-dbus-proxy               0.1.2
system/xdg-utils-cxx                    1.0.1
```

I could bet for xdg-basedir...

Any clue appreciate.

Regards

**Comment by Tonus1** [comment]
Was much more simple. The missing package was xdg from PyPi.

I have to find now why I only have 2 worspaces with an image (and how I can make a buildscript without a setup.py).

**Comment by morrolinux** [comment]
Hi!
I'm glad you figured it out that quickly. 
As for your last edit, I'm not sure what you're trying to convey: is it a bug? If that's the case, please open a separate issue describing the problem you're having and perhaps attacching a screenshot to better understand. 
Thanks!
